Traceback with variables (most recent call last):
  File "...omitted for tests only, abs path.../test_core.py", line 13, in check_
    f()
      kwargs = {'fmt': traceback_with_variables.core.Format(after=0, before=0, brief_files_except=[], color_scheme=None, custom_var_printers=[(<function _var_filter_to_should_print.<locals>.should_print at 0x...omitted for tests only, obj id...>, <function test_var_printers.<locals>.<lambda> at 0x...omitted for tests only, obj id...>), (<function _var_filter_to_should_print.<locals>.should_print at 0x...omitted for tests only, obj id...>, <function test_var_printers.<locals>.<lambda> at 0x...omitted for tests only, obj id...>)], ellipsis_='...', ellipsis_rel_pos=0.7, max_exc_str_len=10000, max_value_str_len=1000, objects_details=1, skip_files_except=[])}
      tb_reg = <bound method Reg.match_tb_text of <tests.test_utils.Reg object at 0x...omitted for tests only, obj id...>>
  File "...omitted for tests only, abs path.../dummies.py", line 92, in f
    return f(
      n = 10001
      s1 = 'short string with n: 10001'
      us = <exception while printing> Traceback (most recent call last):
          ...traceback_with_variables internal stacks...
          File "...omitted for tests only, abs path.../dummies.py", line 29, in __repr__
            raise ValueError("please don't print me")
        ValueError: please don't print me
        
      ...skipped... 1 vars
  File "...omitted for tests only, abs path.../dummies.py", line 86, in f
    return 1 // (n * 0)
      n = 10000
      s1 = 'short string with n: 10000'
      us = <exception while printing> Traceback (most recent call last):
          ...traceback_with_variables internal stacks...
          File "...omitted for tests only, abs path.../dummies.py", line 29, in __repr__
            raise ValueError("please don't print me")
        ValueError: please don't print me
        
      ...skipped... 1 vars
builtins.ZeroDivisionError: integer division or modulo by zero